In [3]:
import numpy as np
import keras

C:\Users\wwwho\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [4]:
from keras.datasets import mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

#print(x_train)
#print(x_train[1])#28*28の行列
#print(len(x_train[1]))#28
#print(len(x_train[2]))#28
#print(len(x_train))#60000
#print(type(x_train))#class 'numpy.ndarray'
#print(x_train.ndim)#3
#print(x_train.shape)# (60000, 28, 28)
#print(x_train.shape[0])# 60000


#print(y_train.ndim)#1
#print(y_train.shape)# (60000,)
#print(y_train.shape[0])# 60000
#print(y_train)#0~9

In [5]:
img_rows, img_cols = 28,28


#print(img_rows * img_cols)# 784
#print(X_train.reshape(X_train.shape[0], img_rows * img_cols).shape)# (60000, 784)

X_train = X_train.reshape(X_train.shape[0], img_rows * img_cols)[0:10000]
X_test = X_test.reshape(X_test.shape[0], img_rows * img_cols)[0:1000]

#print(X_train)
#print(len(X_train[1]))#784
#print(len(X_train[2]))#784
#print(len(X_train))#10000
#print(X_train.ndim)# 2
#print(X_train.shape)# (10000, 784)

#print(X_train.astype('float32'))


X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255

#print(X_train)

In [6]:
from keras.utils import np_utils
Y_train = np_utils.to_categorical(y_train)[0:10000]
Y_test = np_utils.to_categorical(y_test)[0:10000]
#print(Y_train.shape)# (10000, 10)
#print(Y_test.shape)# (10000, 10)
#print(Y_train)
#print(Y_test)

In [7]:
labels = [0,0,1,0]
labels = np_utils.to_categorical(labels)
print(labels)

labels = [0,0,1,0,2,2,0]
labels = np_utils.to_categorical(labels)
print(labels)

labels = [[0,0],[1,0]]
labels = np_utils.to_categorical(labels)
print(labels)

[[1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[[1. 0.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]]]


In [8]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD

In [9]:
input_shape = X_train[0].shape
#print(X_train[0].shape)# (784,)
n_hidden = 20
n_out = len(Y_train[0])
#print(len(Y_train[0]))# 10

In [10]:
model = Sequential()
model.add(Dense(n_hidden, input_shape=input_shape, activation='sigmoid'))
model.add(Dense(n_hidden, input_shape=input_shape, activation='sigmoid'))
model.add(Dense(n_hidden, input_shape=input_shape, activation='sigmoid'))
model.add(Dense(n_hidden, input_shape=input_shape, activation='sigmoid'))
model.add(Dense(n_out, activation='sigmoid'))
model.summary()

Instructions for updating:
Colocations handled automatically by placer.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 20)                15700     
_________________________________________________________________
dense_2 (Dense)              (None, 20)                420       
_________________________________________________________________
dense_3 (Dense)              (None, 20)                420       
_________________________________________________________________
dense_4 (Dense)              (None, 20)                420       
_________________________________________________________________
dense_5 (Dense)              (None, 10)                210       
Total params: 17,170
Trainable params: 17,170
Non-trainable params: 0
_________________________________________________________________


In [11]:
model = Sequential()
model.add(Dense(n_hidden, input_shape=input_shape, activation='sigmoid'))
model.add(Dense(n_out, activation='sigmoid'))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 20)                15700     
_________________________________________________________________
dense_7 (Dense)              (None, 10)                210       
Total params: 15,910
Trainable params: 15,910
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.compile(loss='mean_squared_error', optimizer=SGD(lr=0.1),
             metrics = ['accuracy'])

In [15]:
model.fit(X_train, Y_train, epochs=10, batch_size=128)

Epoch 1/10
10000/10000 [==============================] - 1s 78us/step - loss: 0.0875 - acc: 0.3450
Epoch 2/10
10000/10000 [==============================] - 0s 29us/step - loss: 0.0872 - acc: 0.3506
Epoch 3/10
10000/10000 [==============================] - 0s 29us/step - loss: 0.0870 - acc: 0.3569
Epoch 4/10
10000/10000 [==============================] - 0s 25us/step - loss: 0.0868 - acc: 0.3614
Epoch 5/10
10000/10000 [==============================] - 0s 30us/step - loss: 0.0866 - acc: 0.3661
Epoch 6/10
10000/10000 [==============================] - 0s 25us/step - loss: 0.0863 - acc: 0.3704
Epoch 7/10
10000/10000 [==============================] - 0s 25us/step - loss: 0.0861 - acc: 0.3736
Epoch 8/10
10000/10000 [==============================] - 0s 25us/step - loss: 0.0858 - acc: 0.3747
Epoch 9/10
10000/10000 [==============================] - 0s 24us/step - loss: 0.0856 - acc: 0.3765
Epoch 10/10
10000/10000 [==============================] - 0s 31us/step - loss: 0.0853 - acc: 0.3777

In [16]:
score = model.evaluate(X_train, Y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.09098965400457382
Test accuracy: 0.1069
