In [1]:
def or_func(x1, x2):
    w1 = 1.0
    w2 = 1.0
    theta = 0.5
    h = w1*x1 + w2*x2
    if h > theta:
        return 1
    else:
        return 0

In [2]:
or_func(1,1)

1

In [3]:
or_func(1,0)

1

In [4]:
or_func(0,0)

0

In [5]:
or_func(0,1)

1

In [6]:
or_func(0.5,0)

0

In [8]:
or_func(0.6,0)

1

In [9]:
or_func(0.25,0.26)

1

In [10]:
or_func(0.25,0.25)

0

In [11]:
def and_func(x1, x2):
    w1 = 0.6
    w2 = 0.6
    theta = 1.0
    h = w1*x1 + w2*x2
    if h > theta:
        return 1
    else:
        return 0

In [12]:
and_func(0,0)

0

In [13]:
and_func(1,1)

1

In [14]:
and_func(1,0)

0

In [15]:
def not_(x):
    if x == 1:
        return 0
    else:
        return 1

In [16]:
not_(0)

1

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split

In [38]:
digits = load_digits()
#print(digits.DESCR)
#print(digits)
#print(digits.data.shape)
print(digits.images[3])
print(digits.images[2])
print(digits.images[1])


[[ 0.  0.  7. 15. 13.  1.  0.  0.]
 [ 0.  8. 13.  6. 15.  4.  0.  0.]
 [ 0.  2.  1. 13. 13.  0.  0.  0.]
 [ 0.  0.  2. 15. 11.  1.  0.  0.]
 [ 0.  0.  0.  1. 12. 12.  1.  0.]
 [ 0.  0.  0.  0.  1. 10.  8.  0.]
 [ 0.  0.  8.  4.  5. 14.  9.  0.]
 [ 0.  0.  7. 13. 13.  9.  0.  0.]]
[[ 0.  0.  0.  4. 15. 12.  0.  0.]
 [ 0.  0.  3. 16. 15. 14.  0.  0.]
 [ 0.  0.  8. 13.  8. 16.  0.  0.]
 [ 0.  0.  1.  6. 15. 11.  0.  0.]
 [ 0.  1.  8. 13. 15.  1.  0.  0.]
 [ 0.  9. 16. 16.  5.  0.  0.  0.]
 [ 0.  3. 13. 16. 16. 11.  5.  0.]
 [ 0.  0.  0.  3. 11. 16.  9.  0.]]
[[ 0.  0.  0. 12. 13.  5.  0.  0.]
 [ 0.  0.  0. 11. 16.  9.  0.  0.]
 [ 0.  0.  3. 15. 16.  6.  0.  0.]
 [ 0.  7. 15. 16. 16.  2.  0.  0.]
 [ 0.  0.  1. 16. 16.  3.  0.  0.]
 [ 0.  0.  1. 16. 16.  6.  0.  0.]
 [ 0.  0.  1. 16. 16.  6.  0.  0.]
 [ 0.  0.  0. 11. 16. 10.  0.  0.]]


In [55]:
#plt.gray()
show_no = 3
#plt.imshow(np.reshape(digits.data[show_no],(8,8)))

#print(digits.data[show_no],(8,8))
#print(np.reshape(digits.data[show_no],(8,8)))
#plt.imshow(digits.images[3])
#print(digits.target[show_no])
#print(digits.data[3])
print(digits.data)
print(len(digits.data))
print(len(digits.target))
print(digits.target)
print(digits.target[3])
print(digits.target[1000])
print(digits.target[1200])

#digits.target:0~9の数字が1797個入ったベクトル
#digits.data:8*8の画像の行列(0-9を表す)が1797個入ってる
#digits.images:引数の数字(0-9)を表す8*8の画像の行列を返す

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
1797
1797
[0 1 2 ... 8 9 8]
3
1
7


In [61]:
X_train, X_test, y_train, y_test = train_test_split(
  digits.data, digits.target, random_state=1)

#データをランダムに分割

print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))

#1797を分割
print(X_train)#画像を表す行列:1347個
print(X_test)#画像を表す行列:450個
print(y_train)#0-9の数字:1347個
print(y_test)#0-9の数字:450個

1347
450
1347
450
[[ 0.  0.  7. ...  3.  0.  0.]
 [ 0.  0.  0. ... 11.  6.  0.]
 [ 0.  0.  0. ...  9.  0.  0.]
 ...
 [ 0.  0.  7. ... 13.  2.  0.]
 [ 0.  0.  0. ... 16.  1.  0.]
 [ 0.  0.  8. ...  0.  0.  0.]]
[[ 0.  0.  6. ...  3.  0.  0.]
 [ 0.  8. 13. ...  0.  0.  0.]
 [ 0.  0.  4. ...  6.  0.  0.]
 ...
 [ 0.  0.  8. ...  0.  0.  0.]
 [ 0.  0. 14. ...  1.  0.  0.]
 [ 0.  1. 13. ...  5.  0.  0.]]
[2 6 6 ... 9 1 5]
[1 5 0 7 1 0 6 1 5 4 9 2 7 8 4 6 9 3 7 4 7 1 8 6 0 9 6 1 3 7 5 9 8 3 2 8 8
 1 1 0 7 9 0 0 8 7 2 7 4 3 4 3 4 0 4 7 0 5 5 5 2 1 7 0 5 1 8 3 3 4 0 3 7 4
 3 4 2 9 7 3 2 5 3 4 1 5 5 2 5 2 2 2 2 7 0 8 1 7 4 2 3 8 2 3 3 0 2 9 9 2 3
 2 8 1 1 9 1 2 0 4 8 5 4 4 7 6 7 6 6 1 7 5 6 3 8 3 7 1 8 5 3 4 7 8 5 0 6 0
 6 3 7 6 5 6 2 2 2 3 0 7 6 5 6 4 1 0 6 0 6 4 0 9 3 8 1 2 3 1 9 0 7 6 2 9 3
 5 3 4 6 3 3 7 4 9 2 7 6 1 6 8 4 0 3 1 0 9 9 9 0 1 8 6 8 0 9 5 9 8 2 3 5 3
 0 8 7 4 0 3 3 3 6 3 3 2 9 1 6 9 0 4 2 2 7 9 1 6 7 6 3 7 1 9 3 4 0 6 4 8 5
 3 6 3 1 4 0 4 4 8 7 9 1 5 2 7 0 9 0 4 4 0 1 0 6 4 2 8 

In [226]:
mlp = MLPClassifier(hidden_layer_sizes=19,
                    #activation='logistic',
                    #activation='identity',
                    #activation='tanh',
                    activation='relu',
                    solver='sgd',
                    
                    random_state=1)
#print(mlp)
mlp.fit(X_train, y_train)
print("train accuracy {:.9f}".format(mlp.score(X_train, y_train)))#多い

train accuracy 0.987379362


C:\Users\wwwho\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [138]:

print("test accuracy: {:.4f}".format(mlp.score(X_test, y_test)))#少ない

train accuracy 0.194506310
test accuracy: 0.1933
